services:
  # --- SERVICIO 1: BASE DE DATOS ---
  postgres-db:
    image: postgres:16-alpine
    container_name: app_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-mi_usuario}
      POSTGRES_PASSWORD: ${DB_PASS:-mi_password_secreto}
      POSTGRES_DB: ${DB_NAME:-tienda_db}
    ports:
      - "5432:5432" # Opcional: solo si quieres acceder desde DBeaver/PgAdmin en tu host
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  # --- SERVICIO 2: BACKEND (QUARKUS) ---
  quarkus-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app_backend
    restart: on-failure
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    environment:
      # Conexión JDBC usando el nombre del servicio 'postgres-db' como host
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres-db:5432/${DB_NAME:-tienda_db}
      QUARKUS_DATASOURCE_USERNAME: ${DB_USER:-mi_usuario}
      QUARKUS_DATASOURCE_PASSWORD: ${DB_PASS:-mi_password_secreto}
      # Hibernate: validar esquema en producción, update en dev
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update
    networks:
      - app-network

  # --- SERVICIO 3: FRONTEND (REACT/NGINX) ---
  react-ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: app_frontend
    restart: on-failure
    depends_on:
      - quarkus-api
    ports:
      - "80:80"
    networks:
      - app-network

# Definición de volúmenes persistentes
volumes:
  pg_data:

# Definición de red compartida
networks:
  app-network:
    driver: bridge