services:
  # --- DB (Igual que en prod) ---
  db:
    image: postgres:16-alpine
    container_name: tienda_db_dev
    environment:
      POSTGRES_USER: tienda
      POSTGRES_PASSWORD: tienda
      POSTGRES_DB: tienda_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data_dev:/var/lib/postgresql/data
    networks:
      - dev-network

  # --- BACKEND (Modo Dev - Quarkus) ---
  backend:
    # Usamos una imagen con Maven y JDK instalado, no tu Dockerfile de prod
    image: maven:3.9.6-eclipse-temurin-21
    container_name: tienda_backend_dev
    working_dir: /app
    volumes:
      - ./backend:/app             # <--- MAGIA: Tu código en vivo dentro del container
      - maven_repo:/root/.m2       # Caché de librerías
    ports:
      - "8080:8080"
      - "5005:5005"                # Puerto Debug
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/tienda_db
      QUARKUS_DATASOURCE_USERNAME: tienda
      QUARKUS_DATASOURCE_PASSWORD: tienda
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update
    # Comando para levantar en modo desarrollo
    command: bash -c "mvn quarkus:dev -Dquarkus.http.host=0.0.0.0"
    depends_on:
      - db
    networks:
      - dev-network

  # --- FRONTEND (Modo Dev - Vite) ---
  frontend:
    image: node:20-alpine
    container_name: tienda_frontend_dev
    working_dir: /app
    volumes:
      - ./frontend:/app            # <--- MAGIA: Tu código en vivo
      - /app/node_modules          # Aísla las dependencias de Linux vs Windows
    ports:
      - "5173:5173"                # Puerto de Vite (Dev)
    environment:
      - CHOKIDAR_USEPOLLING=true   # Necesario para Hot Reload en Windows
    # Instala si falta algo y arranca
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - dev-network

volumes:
  pg_data_dev:
  maven_repo:

networks:
  dev-network:
